# Generated by Django 4.0.5 on 2022-09-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='static\\home\\pics-posts\\default-post.png', upload_to='static\\home\\pics-posts'),
        ),
    ]
