# Generated by Django 4.0.5 on 2022-10-04 18:33

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='body',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='posts',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
