# Generated by Django 4.0.5 on 2022-10-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_categories_views_posts_view_counter_posts_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Views',
        ),
    ]
