# Generated by Django 4.0.5 on 2022-10-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='view_counter',
            new_name='likes',
        ),
        migrations.AddField(
            model_name='categories',
            name='project_or_article',
            field=models.CharField(choices=[('Art', 'Article'), ('Proj', 'Project')], default='Art', max_length=7),
        ),
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
