# Generated by Django 4.0.5 on 2022-10-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_view_counter_posts_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='project_or_article',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='slug',
        ),
    ]
