# Generated by Django 4.0.5 on 2022-10-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_posts_project_or_article_posts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='project_or_article',
            field=models.CharField(choices=[('ARTICLE', 'Article'), ('PROJECT', 'Project')], default='ARTICLE', max_length=7),
        ),
    ]
