# Generated by Django 4.0.5 on 2022-10-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_posts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(editable=False, max_length=400, unique=True),
        ),
    ]
