# Generated by Django 4.0.5 on 2022-10-17 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_posts_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='slug',
        ),
    ]
