# Generated by Django 4.0.5 on 2022-11-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_posts_slug_alter_posts_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
