# Generated by Django 4.0.5 on 2022-11-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_posts_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='posts',
            name='project_or_article',
        ),
    ]
