# Generated by Django 4.0.5 on 2022-11-14 14:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_inventions_remove_posts_project_or_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventions',
            name='description_of_project',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='inventions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='inventions',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
