# Generated by Django 4.0.5 on 2022-11-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_inventions_description_of_project_inventions_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventions',
            name='slug',
        ),
        migrations.AddField(
            model_name='inventions',
            name='url',
            field=models.CharField(default='https://github.com/aphxtwin/', max_length=250),
        ),
    ]
