# Generated by Django 4.0.5 on 2022-11-14 19:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_inventions_slug_inventions_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventions',
            name='tech_stack',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
